Docker Volume Custom Resource
sous-chefs/docker pull request #1183
Opened 2021-09-13 14:33 UTC by damacus

# Description

- Move the docker_volume resources to a custom resource
- Add the base partial for all future resources

Signed-off-by: Dan Webb <dan.webb@damacus.io>

## Issues Resolved

NA

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2021-09-14 13:30 UTC, Xorima requested changes
minimum chef version needs bumping?

2021-09-14 15:24 UTC, damacus commented
> minimum chef version needs bumping?

Yup, good spot thank you Chef 16+

https://docs.chef.io/release_notes_client/#resource-partials

2021-09-14 19:04 UTC, ramereth approved these changes

2021-09-15 10:27 UTC, merged

2021-09-15 10:27 UTC, kitchen-porter commented
Released as: [9.0.0](https://github.com/sous-chefs/docker/releases/tag/9.0.0)